name: meet_me_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  auto_route: ^3.2.4
  auto_route_generator: ^3.2.3
  flutter_screenutil: ^5.0.1+2
  sizer: ^2.0.15
  email_validator: ^2.0.1
  provider: ^6.0.1
  loading_overlay: ^0.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_gen_runner: ^4.1.6

flutter_gen: 
  integrations:
    flutter_svg: true

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

